### ISSUE TITLE
When target contains whitespace in /as command

### ISSUE THREAD

**Issue by FoundryModule** [ShoyuVanilla/FoundryVTT-CGMP#18]
Currently, when [target] contains whitespace in `/as [target] [message]` command, such as `/as Shoyu Vanilla Hi!`, the message's alias is `Shoyu`, and content is `Vanilla Hi!`. There are many names that contain more than one word. Therefore, using double quote in [target] can be the solution for this ploblem, like `/as "Shoyu Vanilla" Hi!`. Adding feature that is parsing [target] with whitespace until meeting second double quote if and only if a double quote is following right after `/as ` and keeping current parsing method is recommended. Thank you.

**Comment by ShoyuVanilla** [comment]
You can do it in current version with `/as [Shoyu Vanilla] Hi!` or `/as (Shoyu Vanilla) Hi!`
